---
- name: Configure localization
  hosts: workstation
  become: true

  vars:
    repo_src: files/localization
    sys_dest: /etc

  handlers:
    - name: generates localization
      command: locale-gen
    - import_tasks: handlers/services.yml

  tasks:
    - name: Ensure configuration files copied
      copy:
        src: "{{ item.lsrc }}"
        dest: "{{ item.ldest }}"
        owner: root
        group: root
        mode: "0644"
      loop:
        - {
            lsrc: "{{ repo_src }}/locale.gen",
            ldest: "{{ sys_dest }}/locale.gen",
          }
        - {
            lsrc: "{{ repo_src }}/locale.conf",
            ldest: "{{ sys_dest }}/locale.conf",
          }
      notify:
        - generates localization
        - restart locale

---
- name: Vconsole configuration
  hosts: workstation
  become: true

  handlers:
    - import_tasks: handlers/services.yml

  tasks:
    - name: Ensure font installed
      community.general.pacman:
        name: terminus-font
        state: present
        update_cache: true

    - name: Ensure configuration files copied
      copy:
        src: files/vconsole/vconsole.conf
        dest: /etc/vconsole.conf
        owner: root
        group: root
        mode: "0644"
      notify:
        - restart locale

---
- name: Mkinitcpio configuration
  hosts: workstation
  become: true

  handlers:
    - name: regenerate initramfs
      command: mkinitcpio -P

  tasks:
    - name: Ensure configuration file is copied
      copy:
        src: files/mkinitcpio/mkinitcpio.conf
        dest: /etc/mkinitcpio.conf
        owner: root
        group: root
        mode: "0644"
      notify: regenerate initramfs

---
- name: Configure bootloader
  hosts: workstation
  become: true

  tasks:
    - name: Get LUKS partition UUID
      command: blkid -l -t TYPE=crypto_LUKS -s PARTUUID -o value
      register: blkid_output
      changed_when: false
      failed_when: blkid_output.stdout == ""

    - name: Copy bootloader entries
      template:
        src: templates/limine.conf.j2
        dest: /boot/limine/limine.conf
        owner: root
        group: root
        mode: "0644"
