---
text_editor_packages:
  - neovim
  # NOTE: Lazyvim dependencies:
  # https://www.lazyvim.org/#%EF%B8%8F-requirements
  - git
  - lazygit
  - clang
  - curl
  - fzf
  - ripgrep
  - fd
  - wget # Mason
