---
- name: Get LUKS partition UUID
  ansible.builtin.command:
    cmd: blkid -l -t TYPE=crypto_LUKS -s PARTUUID -o value
  register: bootloader_blkid_output
  changed_when: false
  failed_when: bootloader_blkid_output.rc != 0

- name: Set LUKS partition UUID
  ansible.builtin.set_fact:
    bootloader_luks_uuid: "{{ bootloader_blkid_output.stdout | trim }}"

- name: Print returned UUID
  ansible.builtin.debug:
    msg: "LUKS partition UUID is {{ bootloader_luks_uuid }}"
    verbosity: 1

- name: Ensure directory exists
  ansible.builtin.file:
    state: directory
    path: "{{ bootloader_base_path }}"
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Copy bootloader entries
  ansible.builtin.template:
    src: limine.conf.j2
    dest: "{{ bootloader_base_path }}/limine.conf"
    owner: root
    group: root
    mode: "0644"
  become: true
