---
- name: Start/enable user services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
    scope: user
  loop: "{{ desktop_user_services }}"
  listen: configure services

- name: Start/enable system services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ desktop_system_services }}"
  become: true
  listen: configure services
