---
- name: Check if graphical session is active
  listen: configure services
  block:
    - name: Start/enable user services
      ansible.builtin.service:
        name: "{{ desktop_user_services }}"
        state: started
        enabled: true
        scope: user

    - name: Start/enable system services
      ansible.builtin.service:
        name: "{{ desktop_system_services }}"
        state: started
        enabled: true
      become: true
