---
- name: Reload daemon ({{ config.scope }})
  ansible.builtin.service:
    daemon_reload: true
    scope: "{{ config.scope }}"
  become: "{{ config.scope == 'system' }}"

- name: Enable and optionally start services ({{ config.scope }})
  ansible.builtin.service:
    name: "{{ service }}"
    enabled: true
    state: "{{ 'started' if desktop_graphical_session_active else omit }}"
    scope: "{{ config.scope }}"
  become: "{{ config.scope == 'system' }}"
  loop: "{{ config.services }}"
  loop_control:
    loop_var: service
