---
audio_packages:
  - pipewire
  - wireplumber
  - pipewire-pulse
  - playerctl
  - wiremix
  - pipewire-libcamera
  - spotify-player

audio_user_services_files:
  - playerctld.service
  - spotify.service

audio_user_services:
  - pipewire
  - pipewire-pulse
  - wireplumber
  - playerctld
  - spotify
