---
- name: Install drivers
  ansible.builtin.package:
    name: "{{ audio_packages }}"
    state: present
  become: true

- name: Ensures playerctld directory exists
  ansible.builtin.file:
    path: "{{ audio_systemd_user_path }}"
    state: directory
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
    mode: "0700"
  notify:
    - service daemon reload (user)

- name: Copies playerctld service
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ audio_systemd_user_path }}/{{ item }}"
    owner: "{{ ansible_facts['user_uid'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
    mode: "0644"
  loop: "{{ audio_user_services_files }}"
  notify:
    - service daemon reload (user)

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Start audio services and enable them
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
    scope: user
  loop: "{{ audio_user_services }}"
