---
- name: Install drivers
  ansible.builtin.package:
    name: "{{ gpu_packages }}"
    state: present
  become: true

- name: Enables GuC/HuC for Intel Graphics
  ansible.builtin.copy:
    src: i915.conf
    dest: /etc/modprobe.d/i915.conf
    owner: root
    group: root
    mode: "0644"
  become: true
