---
- name: Check if comment exists
  ansible.builtin.command:
    cmd: "grep -Fxq {{ ufw_docker_ufw_comment | quote }} {{ item }}"
  loop: "{{ ufw_docker_ufw_changed_files }}"
  register: ufw_docker_ufw_comment_check
  changed_when: false
  failed_when: false

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Run ufw-docker installation
  when: >
    (ufw_docker_ufw_comment_check.results
    | selectattr('rc', 'ne', 0)
    | list
    | length > 0) and
    ('docker' in ansible_facts.packages)
  block:
    - name: Download ufw-docker
      ansible.builtin.get_url:
        url: "{{ ufw_docker_ufw_url }}"
        dest: "{{ ufw_docker_ufw_download_path }}"
        mode: "0755"
        force: false
        checksum: "{{ ufw_docker_ufw_checksum }}"
      become: true

    - name: Install ufw-docker
      ansible.builtin.command:
        cmd: "{{ ufw_docker_ufw_download_path }} install --system"
      changed_when: true
      become: true

    - name: Append comment
      ansible.builtin.lineinfile:
        path: "{{ item }}"
        line: "{{ ufw_docker_ufw_comment }}"
        insertafter: EOF
      loop: "{{ ufw_docker_ufw_changed_files }}"
      become: true

    - name: Restarts ufw
      ansible.builtin.service:
        name: ufw
        state: restarted
      become: true
