---
- name: Ensure localization is generated
  ansible.builtin.command:
    cmd: locale-gen
  register: initramfs_localization_output
  changed_when: initramfs_localization_output.rc != 0
  become: true
  listen: regenerate initramfs

- name: Regenerate initramfs
  ansible.builtin.command:
    cmd: mkinitcpio -P
  register: initramfs_regen_output
  changed_when: false
  failed_when: initramfs_regen_output.rc != 0
  become: true
  listen: regenerate initramfs
