---
- name: Check GitHub authentication
  ansible.builtin.command:
    cmd: gh auth status
  register: dev_gh_auth_status
  changed_when: false
  failed_when: false

- name: Authenticate with GitHub
  when: dev_gh_auth_status.rc != 0
  block:
    - name: Get GitHub token from Bitwarden
      ansible.builtin.set_fact:
        dev_github_token: >-
          {{
            lookup(
              'community.general.bitwarden',
              'Github CLI',
              field='password'
            )
          }}
      no_log: true

    - name: Login to GitHub CLI
      ansible.builtin.command:
        cmd: gh auth login --git-protocol ssh --skip-ssh-key --with-token
        stdin: "{{ dev_github_token }}"
      no_log: true
      changed_when: false
