---
- name: Ensure configuration files copied
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - locale.conf
    - locale.gen
  notify:
    - generates localization
    - restart locale
  become: true

- name: Make sure localization is set
  ansible.builtin.meta: flush_handlers
