---
- name: Regenerate initramfs
  ansible.builtin.command:
    cmd: mkinitcpio -P
  register: common_init_regen_output
  changed_when: false
  failed_when: common_init_regen_output.rc != 0
  become: true
  listen: regenerate initramfs

- name: Generates localization
  ansible.builtin.command:
    cmd: locale-gen
  register: common_localization_output
  changed_when: common_localization_output.rc != 0
  listen: generates localization
  become: true

- name: Service daemon reload (system)
  ansible.builtin.service:
    daemon_reload: true
  become: true
  listen: service daemon reload (system)

- name: Service daemon reload (user)
  ansible.builtin.service:
    daemon_reload: true
    scope: user
  listen: service daemon reload (user)

- name: Restart locale
  ansible.builtin.service:
    name: systemd-localed
    state: restarted
  listen: restart locale
  become: true
