---
- name: Install packages
  ansible.builtin.package:
    name: "{{ dotfiles_packages }}"
    state: present
  become: true

- name: Init dotfiles
  ansible.builtin.command:
    cmd: "chezmoi init --apply --promptDefaults --source {{ inventory_dir | dirname }}"
    creates: "{{ dotfiles_chezmoi_config }}"
