---
- name: Ensure configuration files copied
  ansible.builtin.copy:
    src: vconsole.conf
    dest: /etc/vconsole.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - "common : restart locale"
  become: true
