---
galaxy_info:
  license: MIT
  author: Santiago Bernardes
  description: Sets up docker with ufw-docker
  min_ansible_version: "2.2"

dependencies:
  - role: ufw
    when: docker_use_ufw_docker | bool
    vars:
      ufw_use_ufw_docker: true
