#!/usr/bin/env python3


from __future__ import annotations

import argparse
import re
import subprocess
from enum import Enum
from typing import Any, Final, Protocol


class Command:
    _DEFAULT_SUBPROCESS_ARGS: Final[dict[str, Any]] = {
        "check": True,
        "capture_output": True,
        "text": True,
    }

    @classmethod
    def run(cls, *args: str) -> subprocess.CompletedProcess[str]:
        return subprocess.run(args, **cls._DEFAULT_SUBPROCESS_ARGS)


class Osd:
    @staticmethod
    def show(percentage: int, icon: str) -> None:
        Command.run(
            "notify-send",
            "-h",
            f"int:value:{percentage}",
            "-h",
            "boolean:transient:true",
            " ",
            f"{icon}",
        )


class OsdDevice(Protocol):
    def more(self) -> None: ...

    def less(self) -> None: ...

    def toggle(self) -> None: ...

    @property
    def percentage(self) -> int: ...

    def get_icon_for(self, action: Action) -> str: ...


class Action(Enum):
    MORE = "more"
    LESS = "less"
    TOGGLE = "toggle"

    def apply_to(self, device: OsdDevice) -> None:
        {
            Action.MORE: device.more,
            Action.LESS: device.less,
            Action.TOGGLE: device.toggle,
        }[self]()


class Audio(OsdDevice):
    _DEFAULT_SINK: Final[str] = "@DEFAULT_AUDIO_SINK@"
    _VOLUME_PATTERN: Final[re.Pattern[str]] = re.compile(
        r"Volume:\s*([\d.]+)\s*(\[MUTED\])?"
    )

    def more(self) -> None:
        self._execute_command(("set-volume", "-l", "1", self._DEFAULT_SINK, "5%+"))

    def less(self) -> None:
        self._execute_command(("set-volume", self._DEFAULT_SINK, "5%-"))

    def toggle(self) -> None:
        self._execute_command(("set-mute", self._DEFAULT_SINK, "toggle"))

    @property
    def percentage(self) -> int:
        volume: float
        volume, _ = self._get_volume_info()
        return int(volume * 100)

    def get_icon_for(self, action: Action) -> str:
        muted: bool
        _, muted = self._get_volume_info()
        if muted:
            return ""

        match action:
            case Action.MORE | Action.TOGGLE:
                return ""
            case Action.LESS:
                return ""

    def _execute_command(
        self, cmd_args: tuple[str, ...]
    ) -> subprocess.CompletedProcess[str]:
        return Command.run("wpctl", *cmd_args)

    def _get_volume_info(self) -> tuple[float, bool]:
        cmd_output: str = self._execute_command(
            ("get-volume", self._DEFAULT_SINK)
        ).stdout.strip()
        matches = self._VOLUME_PATTERN.search(cmd_output)

        if matches is None:
            raise ValueError(
                "wpctl interface might have changed, run the command and verify the output"
            )
        return float(matches.group(1)), matches.group(2) is not None


class Brightness(OsdDevice):
    def more(self) -> None:
        pass

    def less(self) -> None:
        pass

    def toggle(self) -> None:
        pass

    @property
    def percentage(self) -> int:
        return 0

    def get_icon_for(self, action: Action) -> str:
        return ""


_DEVICES: Final[dict[str, OsdDevice]] = {
    "audio": Audio(),
    "brightness": Brightness(),
}


def parse_args() -> tuple[Action, OsdDevice]:
    parser: argparse.ArgumentParser = argparse.ArgumentParser(
        prog="OSD", description="CLI to control OSD", suggest_on_error=True
    )

    parser.add_argument("action", choices=tuple(action.value for action in Action))
    parser.add_argument("device", choices=tuple(_DEVICES.keys()))
    args: argparse.Namespace = parser.parse_args()

    return Action(args.action), _DEVICES[args.device]


def main() -> None:
    action, device = parse_args()
    action.apply_to(device)
    icon: str = device.get_icon_for(action)
    Osd.show(device.percentage, icon)


if __name__ == "__main__":
    main()
