#!/usr/bin/env python3


from __future__ import annotations
import argparse
import subprocess
from enum import Enum
from typing import Any, Final, Protocol


class OsdDevice(Protocol):
    def more(self) -> None: ...

    def less(self) -> None: ...

    def toggle(self) -> None: ...

    @property
    def percentage(self) -> int: ...

    def get_icon_for(self, action: Action) -> str: ...


class Action(Enum):
    MORE = "more"
    LESS = "less"
    TOGGLE = "toggle"

    def apply_to(self, device: OsdDevice) -> None:
        {
            Action.MORE: device.more,
            Action.LESS: device.less,
            Action.TOGGLE: device.toggle,
        }[self]()


class Audio(OsdDevice):
    _DEFAULT_CMD_OPTS: dict[str, Any] = {
        "capture_output": True,
        "text": True,
        "check": True,
    }

    _DEFAULT_SINK: str = "@DEFAULT_AUDIO_SINK@"

    def more(self) -> None:
        self._execute_command(("set-volume", "-l", "1", self._DEFAULT_SINK, "5%+"))

    def less(self) -> None:
        self._execute_command(("set-volume", self._DEFAULT_SINK, "5%-"))

    def toggle(self) -> None:
        self._execute_command(("set-mute", self._DEFAULT_SINK, "toggle"))

    @property
    def percentage(self) -> int:
        raw_volume: str = self._get_raw_volume()
        volume: float = float(raw_volume.split(":")[1].strip())
        return int(volume * 100)

    def get_icon_for(self, action: Action) -> str:
        return ""

    def _execute_command(
        self, cmd_args: tuple[str, ...]
    ) -> subprocess.CompletedProcess[str]:
        return subprocess.run(("wpctl", *cmd_args), **self._DEFAULT_CMD_OPTS)

    def _get_raw_volume(self) -> str:
        return self._execute_command(("get-volume", self._DEFAULT_SINK)).stdout.strip()


class Brightness(OsdDevice):
    def more(self) -> None:
        pass

    def less(self) -> None:
        pass

    def toggle(self) -> None:
        pass

    @property
    def percentage(self) -> int:
        return 0

    def get_icon_for(self, action: Action) -> str:
        return ""


_DEVICES: Final[dict[str, OsdDevice]] = {
    "audio": Audio(),
    "brightness": Brightness(),
}


def parse_args() -> tuple[Action, OsdDevice]:
    parser: argparse.ArgumentParser = argparse.ArgumentParser(
        prog="OSD", description="CLI to control OSD", suggest_on_error=True
    )

    parser.add_argument("action", choices=tuple(action.value for action in Action))
    parser.add_argument("device", choices=tuple(_DEVICES.keys()))
    args: argparse.Namespace = parser.parse_args()

    return Action(args.action), _DEVICES[args.device]


def main() -> None:
    action, device = parse_args()
    action.apply_to(device)
    icon: str = device.get_icon_for(action)

    subprocess.run(
        (
            "notify-send",
            "-h",
            f"int:value:{device.percentage}",
            "-h",
            "boolean:transient:true",
            " ",
            f"{icon}",
        )
    )


if __name__ == "__main__":
    main()
