---
window_manager_packages:
  - hyprland
  # Systemd startup
  - uwsm
  - libnewt
  # Must have
  - dunst
  - libnotify
  - xdg-desktop-portal-hyprland
  - xdg-desktop-portal-gtk # file picker
  - hyprpolkitagent
  - qt5-wayland
  - qt6-wayland
  - ttf-jetbrains-mono-nerd
  - noto-fonts
  - noto-fonts-emoji
  - noto-fonts-cjk

  # Don't know where these goes
  - hyprpaper
  - hypridle
  - hyprlock
  - hyprshutdown
  - wl-clipboard
  - brightnessctl
  - power-profiles-daemon
  - python-gobject # for powerprofilesctl
  - rofi
  - mpv

window_manager_user_services:
  - hyprpaper
  - hypridle
  - hyprpolkitagent

window_manager_system_services:
  - power-profiles-daemon
