---
- name: Check whether a graphical session is available
  # noqa command-instead-of-module
  ansible.builtin.command:
    cmd: systemctl --user show-environment
  register: desktop_user_environment
  changed_when: false
  failed_when: false

- name: Set fact indicating whether a graphical session exists
  ansible.builtin.set_fact:
    desktop_graphical_session_available: >-
      {{
        'WAYLAND_DISPLAY=' in desktop_user_environment.stdout
        or
        'DISPLAY=' in desktop_user_environment.stdout
      }}

- name: Start and enable desktop session services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
    scope: user
  loop: "{{ desktop_user_session_services }}"
  when: desktop_graphical_session_available

- name: Enable desktop session services only
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    scope: user
  loop: "{{ desktop_user_session_services }}"
  when: not desktop_graphical_session_available
