---
- name: Creates temporary directory
  ansible.builtin.tempfile:
    state: directory
  register: desktop_temp_file

- name: Download Space Grotesk
  ansible.builtin.get_url:
    url: "{{ desktop_space_grotesk_url }}"
    dest: "{{ desktop_temp_file.path }}/font.zip"
    checksum: "{{ desktop_space_grotesk_checksum }}"
    mode: "0644"

- name: Extract font files
  ansible.builtin.unarchive:
    src: "{{ desktop_temp_file.path }}/font.zip"
    dest: "{{ desktop_temp_file.path }}"

- name: Set extracted files path
  ansible.builtin.set_fact:
    desktop_extracted_fonts_path: "{{ desktop_temp_file.path }}/{{ desktop_space_grotesk_extracted_folder }}"

- name: Ensure font directories exists
  ansible.builtin.file:
    path: "{{ desktop_font_path }}/{{ item }}"
    state: directory
    mode: "0555"
    owner: root
    group: root
  become: true
  loop: "{{ desktop_font_extensions }}"

- name: Find all files with a specific extension
  ansible.builtin.find:
    paths: "{{ desktop_extracted_fonts_path }}"
    patterns: "*.{{ item }}"
    recurse: true
  register: desktop_found_font_files
  loop: "{{ desktop_font_extensions }}"

- name: Build flat category/path list
  ansible.builtin.set_fact:
    desktop_font_files: "{{ desktop_font_files | default([]) + [ {'extension': item.0.item, 'path': item.1.path} ] }}"
  loop: "{{ desktop_found_font_files.results | subelements('files') }}"
  loop_control:
    label: "{{ item.1.path }}"

- name: Copies files to their location
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "{{ desktop_font_path }}/{{ item.extension }}"
    mode: "0644"
    owner: root
    group: root
  become: true
  loop: "{{ desktop_font_files }}"

- name: Update font cache
  ansible.builtin.command: fc-cache -f
  become: true
  changed_when: true

- name: Remove temporary directory
  ansible.builtin.file:
    path: "{{ desktop_temp_file.path }}"
    state: absent
