---
- name: Check GitHub authentication
  ansible.builtin.command:
    cmd: gh auth status
  register: git_cli_auth_status
  changed_when: false
  failed_when: false

- name: Authenticate with GitHub
  when: git_cli_auth_status.rc != 0
  block:
    - name: GitHub login
      ansible.builtin.import_tasks:
        file: login_github.yml


- name: Setup SSH
  ansible.builtin.import_tasks:
    file: ssh.yml
