---
- name: Check GitHub authentication
  ansible.builtin.command:
    cmd: gh auth status
  register: git_cli_auth_status
  changed_when: false
  failed_when: false

- name: Authenticate with GitHub
  when: git_cli_auth_status.rc != 0
  block:
    - name: Get GitHub token from Bitwarden
      ansible.builtin.set_fact:
        git_token: >-
          {{
            lookup(
              'community.general.bitwarden',
              {{ git_bw_item_name }},
              field='password',
              result_count=1
            ) | first
          }}
      no_log: true

    - name: Login to GitHub CLI
      ansible.builtin.command:
        cmd: gh auth login --git-protocol ssh --skip-ssh-key --with-token
        stdin: "{{ git_token | trim }}"
      no_log: true
      changed_when: false
