---
- name: Call GitHub's public ssh keys endpoint
  ansible.builtin.uri:
    url: "{{ git_ssh_keys_endpoint }}"
    headers:
      Accept: "{{ git_ssh_keys_api_accept_header }}"
      X-GitHub-Api-Version: "{{ git_ssh_keys_api_version }}"
    method: GET
    body_format: json
  register: git_api_response

- name: Add ssh keys to known_hosts
  ansible.builtin.known_hosts:
    host: "{{ git_hub_ssh_host }}"
    key: "{{ git_hub_ssh_host }} {{ item }}"
    state: present
  loop: "{{ git_api_response.json.ssh_keys }}"

- name: Get repository SSH URL
  ansible.builtin.command:
    cmd: >
      gh repo view
      "{{ git_automation_repo_name }}"
      --json sshUrl
      --jq .sshUrl
  register: git_ssh_url
  changed_when: false

- name: Debug
  ansible.builtin.debug:
    msg: "SSH url is: {{ git_ssh_url.stdout }}"
    verbosity: 1

- name: Ensure SSH origin
  community.general.git_config:
    repo: "{{ inventory_dir | dirname }}"
    name: remote.origin.url
    value: "{{ git_ssh_url.stdout | trim }}"
    scope: local
    state: present
